AWSTemplateFormatVersion: 2010-09-09
Description: sam-sentiment-stream

Transform:
- AWS::Serverless-2016-10-31

Metadata:
  AWS::CloudFormation::Interface:
   ParameterGroups:
     - Label: {default: 'Optional parameters'}
       Parameters:
         - ProjectName
         - StreamName
         - TopicARN

Parameters:
  ProjectName:
   Type: String
   Description: 'Name of the project'
   Default: 'sam-sentiment'
  StreamName:
   Type: String
   Description: 'Please input the Dynamo DB Stream name'
  TopicARN:
   Type: String
   Description: 'Please input the topic arn'

Resources:
  
  ProcessDynamoDBStream:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-stream'
      CodeUri: src
      Handler: process.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies: 
        - AWSLambdaBasicExecutionRole
        - AmazonSNSFullAccess
      Environment:
        Variables:
          TOPIC: !Sub '${TopicARN}'
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !Sub '${StreamName}'
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
