AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for sam-sentiment-socket that has the DynamoDB table and Lambda
  functions needed to perform websocket communication

Metadata:
  AWS::CloudFormation::Interface:
   ParameterGroups:
     - Label: {default: 'Optional parameters'}
       Parameters:
         - ProjectName

Parameters:
  ProjectName:
   Type: String
   Description: 'Name of the project'
   Default: 'sam-sentiment-socket'

Resources:

  # Define Topic
  SentimentSubscriptionTopic:
   Type: AWS::SNS::Topic
   Properties:
     TopicName: !Sub '${ProjectName}'
     Subscription:
       - Protocol: sqs
         Endpoint: !GetAtt SentimentSubscriptionQueue.Arn
     Tags:
       - Key: Name
         Value: !Sub '${ProjectName}'

  # Define the SQS queue
  SentimentSubscriptionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ProjectName}'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}'

  # Define SNS to SQS Policy
  SnsToSqsPolicy:
    Type: AWS::SQS::QueuePolicy      
    Properties:    
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "Allow SNS publish to SQS"
            Effect: Allow
            Principal: 
              Service: "sns.amazonaws.com"
            Resource: !GetAtt SentimentSubscriptionQueue.Arn
            Action: SQS:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SentimentSubscriptionTopic
      Queues:
        - Ref: SentimentSubscriptionQueue

  SentimentWebSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: SentimentWebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SentimentWebSocket
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectInteg

  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SentimentWebSocket
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SentimentWebSocket
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DisconnectInteg

  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SentimentWebSocket
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations

  SendRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SentimentWebSocket
      RouteKey: sendmessage
      AuthorizationType: NONE
      OperationName: SendRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref SendInteg

  SendInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SentimentWebSocket
      Description: Send Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendMessageFunction.Arn}/invocations

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ConnectRoute
    - SendRoute
    - DisconnectRoute
    Properties:
      ApiId: !Ref SentimentWebSocket

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref SentimentWebSocket
      
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "symbol"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "symbol"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      
  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/connection_handler
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Select [1, !Split ['/', !GetAtt ConnectionsTable.Arn]]
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Select [1, !Split ['/', !GetAtt ConnectionsTable.Arn]]

  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - SentimentWebSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnConnectFunction
      Principal: apigateway.amazonaws.com

  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/connection_handler
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Select [1, !Split ['/', !GetAtt ConnectionsTable.Arn]]
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Select [1, !Split ['/', !GetAtt ConnectionsTable.Arn]]

  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - SentimentWebSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnDisconnectFunction
      Principal: apigateway.amazonaws.com

  SendMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/message_handler
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Select [1, !Split ['/', !GetAtt ConnectionsTable.Arn]]
          TOPIC: !Ref SentimentSubscriptionTopic
      Policies:
        - AmazonSNSFullAccess
        - DynamoDBCrudPolicy:
            TableName: !Select [1, !Split ['/', !GetAtt ConnectionsTable.Arn]]
        - Statement:
          - Effect: Allow
            Action:
            - 'execute-api:ManageConnections'
            Resource:
            - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${SentimentWebSocket}/*'

  SendMessagePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - SentimentWebSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SendMessageFunction
      Principal: apigateway.amazonaws.com

Outputs:

  WebEndpoint:
    Description: "API Gateway endpoint URL for sending message"
    Value: !Join [ '', [ 'https://', !Ref SentimentWebSocket, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref 'Stage'] ]

  WebSocketURI:
    Description: "The WSS Protocol URI to connect"
    Value: !Join [ '', [ 'wss://', !Ref SentimentWebSocket, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref 'Stage'] ]

  ConnectionsTableArn:
    Description: "Connections table name"
    Value: !Select [1, !Split ['/', !GetAtt ConnectionsTable.Arn]]

  SQSqueueURL:
    Description: SQS queue URL
    Value: !Ref SentimentSubscriptionQueue