AWSTemplateFormatVersion: 2010-09-09
Description: sam-sentiment-quote

Transform:
- AWS::Serverless-2016-10-31

Metadata:
  AWS::CloudFormation::Interface:
   ParameterGroups:
     - Label: {default: 'Optional parameters'}
       Parameters:
         - ProjectName
         - TableName
         - ApiKey

Parameters:
  ProjectName:
   Type: String
   Description: 'Name of the project'
   Default: 'sam-sentiment'
  TableName:
   Type: String
   Description: 'Please input the table name'
  ApiKey:
   Type: String
   Description: 'Please input the api key'

Resources:
  StockQuoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-quote'
      Description: Get the Symbol latest quote
      # CodeUri: ./
      Handler: src/process.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub '${TableName}'
      Environment:
        Variables:
          TABLE_NAME: !Sub '${TableName}'
          ALPHAVANTAGE_API_KEY: !Sub '${ApiKey}'

Outputs:
  StockQuoteFunction:
    Description: "Sentiment Stock Quote Lambda Function ARN"
    Value: !GetAtt StockQuoteFunction.Arn